### ISSUE TITLE
git-initializer should take the commit-id in account even when the reference is specified

### ISSUE THREAD

**Issue by thomschke** [brigadecore/brigade-github-gateway#39]
Currently, the Commit-Id is not taken into account when the Commit-Reference is specified.

https://github.com/Azure/brigade/blob/01add9cb40a3c3e404113f51158c20f5af83600c/git-sidecar/rootfs/clone.sh#L13-L14

###

Problems:

- If a pipeline with many jobs runs for a long time and a new commit on this branch occurs in between, then it's possible that some jobs of the pipeline runs on different source versions.
- The Brig CLI run command has a default value "`master`" for the `ref`-parameter. 
https://github.com/Azure/brigade/blob/01add9cb40a3c3e404113f51158c20f5af83600c/brig/cmd/brig/commands/run.go#L28
https://github.com/Azure/brigade/blob/01add9cb40a3c3e404113f51158c20f5af83600c/brig/cmd/brig/commands/run.go#L58 That's why vcs-sidecar will always perform with a reference, so the `commit`-parameter is passed only to the event-object, but has no meaning for source version.

**Comment by krancour** [comment]
I've verified that in all places possible, this gateway sets a commit/sha on the events it sends to Brigade.

The only cases where it doesn't are those where the webhook does not include this information. Specifically, these are the webhooks that indicate the creation of a branch, tag, or release.

Since tags and releases are inherently references to a specific commit, it's actually a non-issue in those cases.

For the one remaining case-- creation of a new branch, it is what it is. The webhook says a branch was created and it doesn't say what commit is at the head of that branch. So that's what gets passed on to Brigade.
